In [1]:
#Task11

#Apply one hot encoding technique

import numpy as np
from sklearn.preprocessing import OneHotEncoder

#exmples categorical data

categories=np.array(['apple','banana','orange','apple']).reshape(-1,1)

#apply one hot encoding 

encoder=OneHotEncoder(sparse=False)
one_hot_encoded=encoder.fit_transform(categories)

print('Original Categories;\n',categories.flatten())
print('One-Hot Encoded:\n',one_hot_encoded)



Original Categories;
 ['apple' 'banana' 'orange' 'apple']
One-Hot Encoded:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]


C:\Users\DELL\anaconda3\Lib\site-packages\sklearn\preprocessing\_encoders.py:972: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


In [ ]:
#task 12
#deep learning framework for object detection
pip install opencv-python


import cv2
from matplotlib import pyplot as plt
import urllib.request


img=cv2.imread(r"C:\Users\DELL\Desktop\sign.jpg")

#openCV opens images as RGB
#but we want it as RGB we'll 
#also need a grayscale version
# Convert to grayscale
img_gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

# Convert to RGB (optional)
img_rgb = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)


#use minSize because for not
#bothering with extra-small
#dots that would look like STOP signs

stop_data = cv2.CascadeClassifier('stop_data.xml')
found = stop_data.detectMultiScale(img_gray,minSize=(20,20))


#Dont do anything if there's
#no sign

amount_found = len(found)

if amount_found !=0:
    #there may be more than one
    #sign in the image
    for (x,y,width,height) in found:
        #we draw a green rectangle around
        #every recognized sign
        cv2.rectangle(img_rgb,(x,y),(x+height,y_width),(0,255,0),5)
        
        
#creates the environment of
#the picture and shows it

plt.subplot(1,1,1)
plt.imshow(img_rgb)
plt.show()